import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const supabaseUrl = 'https://yhmcpfxakmxryqnwpiaa.supabase.co';
const serviceRoleKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlobWNwZnhha214cnlxbndwaWFhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDg2ODYzNSwiZXhwIjoyMDkwNDQ0NjM1fQ.x0YQRjwyTF6Gcxnn__ruYJZ_aMFl6QvFnAG31G4g6jA';

const supabase = createClient(supabaseUrl, serviceRoleKey, {
  auth: { persistSession: false }
});

const rows = [
  // ALMANYA - Aile/Arkadaş Ziyareti
  { country: 'Almanya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Pasaportun orijinali (son 10 yıl içinde alınmış)', delivery_type: 'physical', order_num: 1 },
  { country: 'Almanya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Pasaport fotokopisi', delivery_type: 'digital', order_num: 2 },
  { country: 'Almanya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Kimlik fotokopisi', delivery_type: 'digital', order_num: 3 },
  { country: 'Almanya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: '2 adet biyometrik fotoğraf (35x45mm, beyaz fon)', delivery_type: 'physical', order_num: 4 },
  { country: 'Almanya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Vize başvuru formu (Videx sistemi / imzalı, 2 nüsha)', delivery_type: 'company', order_num: 5 },
  { country: 'Almanya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Tam vukuatlı nüfus kayıt örneği (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 6 },
  { country: 'Almanya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 7 },
  { country: 'Almanya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Gidiş-dönüş uçak bileti rezervasyonu', delivery_type: 'digital', order_num: 8 },
  { country: 'Almanya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Seyahat sağlık sigortası (min. 30.000 €, tüm Schengen geçerli)', delivery_type: 'digital', order_num: 9 },
  { country: 'Almanya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Son 3 aylık banka hesap dökümü (banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 10 },
  { country: 'Almanya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: "Almanya'daki ev sahibinden davet mektubu — Verpflichtungserklärung (yabancılar dairesinden onaylı)", delivery_type: 'digital', order_num: 11 },
  { country: 'Almanya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Ev sahibinin pasaport / oturma izni fotokopisi', delivery_type: 'digital', order_num: 12 },
  { country: 'Almanya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Akrabalık ilişkisini gösteren belge (tercümeli, Apostilli)', delivery_type: 'digital', order_num: 13 },
  // ALMANYA - Eğitim/Öğrenci
  { country: 'Almanya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Pasaportun orijinali', delivery_type: 'physical', order_num: 1 },
  { country: 'Almanya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Pasaport fotokopisi', delivery_type: 'digital', order_num: 2 },
  { country: 'Almanya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Kimlik fotokopisi', delivery_type: 'digital', order_num: 3 },
  { country: 'Almanya', visa_type: 'Eğitim/Öğrenci', doc_name: '2 adet biyometrik fotoğraf (35x45mm)', delivery_type: 'physical', order_num: 4 },
  { country: 'Almanya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Vize başvuru formu (Videx sistemi / imzalı)', delivery_type: 'company', order_num: 5 },
  { country: 'Almanya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Tam vukuatlı nüfus kayıt örneği (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 6 },
  { country: 'Almanya', visa_type: 'Eğitim/Öğrenci', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 7 },
  { country: 'Almanya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Gidiş-dönüş uçak bileti rezervasyonu', delivery_type: 'digital', order_num: 8 },
  { country: 'Almanya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Seyahat sağlık sigortası (min. 30.000 €)', delivery_type: 'digital', order_num: 9 },
  { country: 'Almanya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Okul/üniversite kabul belgesi veya davet yazısı', delivery_type: 'digital', order_num: 10 },
  { country: 'Almanya', visa_type: 'Eğitim/Öğrenci', doc_name: "Öğrenci belgesi (Türkiye'deki okul)", delivery_type: 'digital', order_num: 11 },
  { country: 'Almanya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Burs belgesi (varsa)', delivery_type: 'digital', order_num: 12 },
  { country: 'Almanya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Veli gelir belgesi / maaş bordrosu (son 3 ay, tercümeli)', delivery_type: 'digital', order_num: 13 },
  { country: 'Almanya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Veli/sponsor banka hesap dökümü (son 3 ay, banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 14 },
  { country: 'Almanya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Finansal geçim kanıtı: Bloke hesap (Sperrkonto) belgesi veya taahhütname (min. 11.904 €/yıl — 992 €/ay — 2026)', delivery_type: 'digital', order_num: 15 },
  // ALMANYA - Ticari/İş
  { country: 'Almanya', visa_type: 'Ticari/İş', doc_name: 'Pasaportun orijinali', delivery_type: 'physical', order_num: 1 },
  { country: 'Almanya', visa_type: 'Ticari/İş', doc_name: 'Pasaport fotokopisi', delivery_type: 'digital', order_num: 2 },
  { country: 'Almanya', visa_type: 'Ticari/İş', doc_name: 'Kimlik fotokopisi', delivery_type: 'digital', order_num: 3 },
  { country: 'Almanya', visa_type: 'Ticari/İş', doc_name: '2 adet biyometrik fotoğraf', delivery_type: 'physical', order_num: 4 },
  { country: 'Almanya', visa_type: 'Ticari/İş', doc_name: 'Vize başvuru formu (Videx sistemi / imzalı)', delivery_type: 'company', order_num: 5 },
  { country: 'Almanya', visa_type: 'Ticari/İş', doc_name: 'Tam vukuatlı nüfus kayıt örneği (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 6 },
  { country: 'Almanya', visa_type: 'Ticari/İş', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 7 },
  { country: 'Almanya', visa_type: 'Ticari/İş', doc_name: 'Gidiş-dönüş uçak bileti rezervasyonu', delivery_type: 'digital', order_num: 8 },
  { country: 'Almanya', visa_type: 'Ticari/İş', doc_name: 'Seyahat sağlık sigortası (min. 30.000 €)', delivery_type: 'digital', order_num: 9 },
  { country: 'Almanya', visa_type: 'Ticari/İş', doc_name: "Almanya'daki iş ortağından davet mektubu (şirket antetli, İngilizce/Almanca)", delivery_type: 'digital', order_num: 10 },
  { country: 'Almanya', visa_type: 'Ticari/İş', doc_name: 'İşveren görev yazısı (izin tarihleri, maaş, pozisyon belirtir)', delivery_type: 'digital', order_num: 11 },
  { country: 'Almanya', visa_type: 'Ticari/İş', doc_name: 'Maaş bordrosu (son 3 ay)', delivery_type: 'digital', order_num: 12 },
  { country: 'Almanya', visa_type: 'Ticari/İş', doc_name: 'Şirket faaliyet belgesi (son 3 ay içinde alınmış, e-imzalı/orijinal)', delivery_type: 'digital', order_num: 13 },
  { country: 'Almanya', visa_type: 'Ticari/İş', doc_name: 'Vergi levhası', delivery_type: 'digital', order_num: 14 },
  { country: 'Almanya', visa_type: 'Ticari/İş', doc_name: 'Ticaret sicil gazetesi (son 6 ay içinde alınmış, tercümeli)', delivery_type: 'digital', order_num: 15 },
  { country: 'Almanya', visa_type: 'Ticari/İş', doc_name: 'İmza sirküleri (Apostilli, tercümeli)', delivery_type: 'digital', order_num: 16 },
  { country: 'Almanya', visa_type: 'Ticari/İş', doc_name: 'Son 3 aylık banka hesap dökümü (banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 17 },
  // ALMANYA - Turistik
  { country: 'Almanya', visa_type: 'Turistik', doc_name: 'Pasaportun orijinali', delivery_type: 'physical', order_num: 1 },
  { country: 'Almanya', visa_type: 'Turistik', doc_name: 'Pasaport fotokopisi', delivery_type: 'digital', order_num: 2 },
  { country: 'Almanya', visa_type: 'Turistik', doc_name: 'Kimlik fotokopisi', delivery_type: 'digital', order_num: 3 },
  { country: 'Almanya', visa_type: 'Turistik', doc_name: '2 adet biyometrik fotoğraf', delivery_type: 'physical', order_num: 4 },
  { country: 'Almanya', visa_type: 'Turistik', doc_name: 'Vize başvuru formu (Videx sistemi / imzalı)', delivery_type: 'company', order_num: 5 },
  { country: 'Almanya', visa_type: 'Turistik', doc_name: 'Tam vukuatlı nüfus kayıt örneği (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 6 },
  { country: 'Almanya', visa_type: 'Turistik', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 7 },
  { country: 'Almanya', visa_type: 'Turistik', doc_name: 'Gidiş-dönüş uçak bileti rezervasyonu', delivery_type: 'digital', order_num: 8 },
  { country: 'Almanya', visa_type: 'Turistik', doc_name: 'Otel / konaklama rezervasyonu', delivery_type: 'digital', order_num: 9 },
  { country: 'Almanya', visa_type: 'Turistik', doc_name: 'Seyahat sağlık sigortası (min. 30.000 €)', delivery_type: 'digital', order_num: 10 },
  { country: 'Almanya', visa_type: 'Turistik', doc_name: 'İşveren İzin/Görev Yazısı — ZORUNLU (ıslak imzalı ve kaşeli; işe başlangıç tarihi, maaş, görev ve izin tarihleri belirtilmeli)', delivery_type: 'digital', order_num: 11 },
  { country: 'Almanya', visa_type: 'Turistik', doc_name: 'SGK İşe Giriş Bildirgesi — ZORUNLU (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 12 },
  { country: 'Almanya', visa_type: 'Turistik', doc_name: 'SGK Hizmet Dökümü (e-devlet, barkodlu; tüm sigorta geçmişini kapsar)', delivery_type: 'digital', order_num: 13 },
  { country: 'Almanya', visa_type: 'Turistik', doc_name: 'Maaş bordrosu (son 3 ay) veya gelir belgesi', delivery_type: 'digital', order_num: 14 },
  { country: 'Almanya', visa_type: 'Turistik', doc_name: 'Son 3 aylık banka hesap dökümü (banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 15 },
  // ALMANYA - Çalışma/İş Vizesi
  { country: 'Almanya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Pasaportun orijinali (en az 2 boş sayfa)', delivery_type: 'physical', order_num: 1 },
  { country: 'Almanya', visa_type: 'Çalışma/İş Vizesi', doc_name: '2 adet biyometrik fotoğraf (35x45mm)', delivery_type: 'physical', order_num: 2 },
  { country: 'Almanya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Ulusal Vize (D Tipi) Başvuru Formu (Videx sistemi, imzalı 2 nüsha)', delivery_type: 'company', order_num: 3 },
  { country: 'Almanya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 4 },
  { country: 'Almanya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Tam vukuatlı nüfus kayıt örneği (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 5 },
  { country: 'Almanya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Adli sicil kaydı (e-devlet, Apostilli, Almanca/İngilizce tercümeli)', delivery_type: 'digital', order_num: 6 },
  { country: 'Almanya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'İş sözleşmesi veya iş teklifi (Erklärung zum Beschäftigungsverhältnis — BA formatında)', delivery_type: 'digital', order_num: 7 },
  { country: 'Almanya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Maaş yeterliliği belgesi (Mavi Kart std: min. 50.700 €/yıl brüt; STEM/darboğaz: 45.934,20 €; 45 yaş üstü: 55.770 € — 2026)', delivery_type: 'digital', order_num: 8 },
  { country: 'Almanya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Diploma aslı (Apostilli) + noterde onaylı Almanca tercümesi', delivery_type: 'digital', order_num: 9 },
  { country: 'Almanya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Anabin "H+" sonucu veya ZAB denklik belgesi', delivery_type: 'digital', order_num: 10 },
  { country: 'Almanya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Üniversite transkripti (Apostilli) + Almanca tercümesi', delivery_type: 'digital', order_num: 11 },
  { country: 'Almanya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Mesleki uygulama izni (doktor, mühendis vb. regüle meslekler için yetkili makam onayı)', delivery_type: 'digital', order_num: 12 },
  { country: 'Almanya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Güncel CV / Özgeçmiş (Europass formatı, Almanca veya İngilizce)', delivery_type: 'digital', order_num: 13 },
  { country: 'Almanya', visa_type: 'Çalışma/İş Vizesi', doc_name: "Motivasyon mektubu (pozisyonu ve Almanya'da çalışma gerekçesini açıklar)", delivery_type: 'digital', order_num: 14 },
  { country: 'Almanya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Incoming sağlık sigortası (vize başvurusu ve ilk girişi kapsar)', delivery_type: 'digital', order_num: 15 },
  { country: 'Almanya', visa_type: 'Çalışma/İş Vizesi', doc_name: "Konaklama belgesi (Almanya'daki adres / kira sözleşmesi)", delivery_type: 'digital', order_num: 16 },
  // AMERİKA - Aile/Arkadaş Ziyareti
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Pasaportun orijinali', delivery_type: 'physical', order_num: 1 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: '1 adet biyometrik fotoğraf (5×5 cm, beyaz fon)', delivery_type: 'physical', order_num: 2 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'DS-160 başvuru formu (barkodlu onay sayfası çıktısı)', delivery_type: 'company', order_num: 3 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Randevu onay belgesi', delivery_type: 'digital', order_num: 4 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Kimlik fotokopisi', delivery_type: 'digital', order_num: 5 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Nüfus kayıt örneği (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 6 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: "ABD'deki ev sahibinden davet mektubu (İngilizce)", delivery_type: 'digital', order_num: 7 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Ev sahibinin pasaport / Green Card / oturma izni fotokopisi', delivery_type: 'digital', order_num: 8 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Akrabalık belgesi (tercümeli)', delivery_type: 'digital', order_num: 9 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Maaş bordrosu veya gelir belgesi', delivery_type: 'digital', order_num: 10 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Son 3 aylık banka hesap dökümü (banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 11 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Vize ücreti ödeme makbuzu (MRV ücreti — 30 Mayıs 2026 öncesi 185 USD; 30 Mayıs 2026 sonrası 205 USD)', delivery_type: 'digital', order_num: 12 },
  // AMERİKA - Eğitim/Öğrenci
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Eğitim/Öğrenci', doc_name: 'Pasaportun orijinali', delivery_type: 'physical', order_num: 1 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Eğitim/Öğrenci', doc_name: '1 adet biyometrik fotoğraf (5×5 cm, beyaz fon)', delivery_type: 'physical', order_num: 2 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Eğitim/Öğrenci', doc_name: 'DS-160 başvuru formu (barkodlu onay sayfası çıktısı)', delivery_type: 'company', order_num: 3 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Eğitim/Öğrenci', doc_name: 'Randevu onay belgesi', delivery_type: 'digital', order_num: 4 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Eğitim/Öğrenci', doc_name: 'SEVIS I-20 formu (okuldan temin edilir)', delivery_type: 'digital', order_num: 5 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Eğitim/Öğrenci', doc_name: 'SEVIS ücreti ödeme makbuzu (350 USD — fmjfee.com)', delivery_type: 'digital', order_num: 6 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Eğitim/Öğrenci', doc_name: 'Amerikan okul/üniversite kabul belgesi', delivery_type: 'digital', order_num: 7 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Eğitim/Öğrenci', doc_name: "Öğrenci belgesi (Türkiye'deki okul)", delivery_type: 'digital', order_num: 8 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Eğitim/Öğrenci', doc_name: 'İngilizce dil yeterlilik belgesi (TOEFL / IELTS vb.)', delivery_type: 'digital', order_num: 9 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Eğitim/Öğrenci', doc_name: 'Burs belgesi (varsa)', delivery_type: 'digital', order_num: 10 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Eğitim/Öğrenci', doc_name: 'Veli gelir belgesi / maaş bordrosu', delivery_type: 'digital', order_num: 11 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Eğitim/Öğrenci', doc_name: 'Son 6 aylık veli/sponsor banka hesap dökümü (banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 12 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Eğitim/Öğrenci', doc_name: 'Vize ücreti ödeme makbuzu (185 USD — MRV ücreti)', delivery_type: 'digital', order_num: 13 },
  // AMERİKA - Ticari/İş
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Ticari/İş', doc_name: 'Pasaportun orijinali', delivery_type: 'physical', order_num: 1 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Ticari/İş', doc_name: '1 adet biyometrik fotoğraf (5×5 cm, beyaz fon)', delivery_type: 'physical', order_num: 2 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Ticari/İş', doc_name: 'DS-160 başvuru formu (barkodlu onay sayfası çıktısı)', delivery_type: 'company', order_num: 3 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Ticari/İş', doc_name: 'Randevu onay belgesi', delivery_type: 'digital', order_num: 4 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Ticari/İş', doc_name: 'Kimlik fotokopisi', delivery_type: 'digital', order_num: 5 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Ticari/İş', doc_name: 'Nüfus kayıt örneği (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 6 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Ticari/İş', doc_name: "ABD'deki iş ortağından davet mektubu (şirket antetli, İngilizce)", delivery_type: 'digital', order_num: 7 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Ticari/İş', doc_name: 'İşveren görev yazısı (şirket antetli, İngilizce — rol, süre, maaş belirtir)', delivery_type: 'digital', order_num: 8 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Ticari/İş', doc_name: 'Vize dilekçesi (şirket antetli, İngilizce)', delivery_type: 'digital', order_num: 9 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Ticari/İş', doc_name: 'Şirket faaliyet belgesi (İngilizce)', delivery_type: 'digital', order_num: 10 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Ticari/İş', doc_name: 'Vergi levhası', delivery_type: 'digital', order_num: 11 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Ticari/İş', doc_name: 'Ticaret sicil gazetesi (İngilizce tercümeli)', delivery_type: 'digital', order_num: 12 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Ticari/İş', doc_name: 'İmza sirküleri (Apostilli, İngilizce tercümeli)', delivery_type: 'digital', order_num: 13 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Ticari/İş', doc_name: 'Son 3 aylık banka hesap dökümü (banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 14 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Ticari/İş', doc_name: 'Vize ücreti ödeme makbuzu (185 USD)', delivery_type: 'digital', order_num: 15 },
  // AMERİKA - Turistik
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Turistik', doc_name: 'Pasaportun orijinali (+ varsa eski pasaportlar)', delivery_type: 'physical', order_num: 1 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Turistik', doc_name: '1 adet biyometrik fotoğraf (5×5 cm, beyaz fon)', delivery_type: 'physical', order_num: 2 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Turistik', doc_name: 'DS-160 başvuru formu (online, barkodlu onay sayfası çıktısı)', delivery_type: 'company', order_num: 3 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Turistik', doc_name: 'Randevu onay belgesi', delivery_type: 'digital', order_num: 4 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Turistik', doc_name: 'Kimlik fotokopisi', delivery_type: 'digital', order_num: 5 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Turistik', doc_name: 'Tam vukuatlı nüfus kayıt örneği (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 6 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Turistik', doc_name: 'Seyahat planı / gidiş-dönüş uçak rezervasyonu (görüşmede rezervasyon yeterli; kesin bilet alınmaması tavsiye edilir)', delivery_type: 'digital', order_num: 7 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Turistik', doc_name: 'Konaklama planı / otel rezervasyonu (görüşmede sorulabilir; iade edilemez rezervasyon yapılmaması önerilir)', delivery_type: 'digital', order_num: 8 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Turistik', doc_name: 'İşveren izin yazısı (görev, maaş, izin tarihleri — İngilizce)', delivery_type: 'digital', order_num: 9 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Turistik', doc_name: 'Maaş bordrosu (son 3 ay)', delivery_type: 'digital', order_num: 10 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Turistik', doc_name: 'SGK hizmet dökümü (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 11 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Turistik', doc_name: 'Son 3 aylık banka hesap dökümü (banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 12 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Turistik', doc_name: 'Vize dilekçesi (kişisel, İngilizce)', delivery_type: 'digital', order_num: 13 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Turistik', doc_name: 'Vize ücreti ödeme makbuzu (185 USD)', delivery_type: 'digital', order_num: 14 },
  // AMERİKA - Çalışma/İş Vizesi
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Pasaportun orijinali (+ varsa eski pasaportlar)', delivery_type: 'physical', order_num: 1 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Çalışma/İş Vizesi', doc_name: '1 adet biyometrik fotoğraf (5×5 cm, beyaz fon)', delivery_type: 'physical', order_num: 2 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Çalışma/İş Vizesi', doc_name: 'DS-160 Onay Sayfası (barkodlu online başvuru formu)', delivery_type: 'company', order_num: 3 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Randevu onay belgesi (konsolosluk mülakatı için)', delivery_type: 'digital', order_num: 4 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Çalışma/İş Vizesi', doc_name: "I-797 Onay Belgesi (Notice of Approval — USCIS'in işveren adına onayı)", delivery_type: 'digital', order_num: 5 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Çalışma/İş Vizesi', doc_name: "I-129 Formu kopyası (işverenin USCIS'e sunduğu geçici işçi dilekçesi)", delivery_type: 'digital', order_num: 6 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Çalışma/İş Vizesi', doc_name: 'LCA (Labor Condition Application — ABD Çalışma Bakanlığı onaylı)', delivery_type: 'digital', order_num: 7 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Çalışma/İş Vizesi', doc_name: 'MRV Vize Ücreti Dekontu (H-1B konsüler stamp için 205 USD)', delivery_type: 'digital', order_num: 8 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Çalışma/İş Vizesi', doc_name: 'İş teklifi ve görev tanımı mektubu (şirket antetli, ıslak imzalı, İngilizce — rol, maaş, süre belirtir)', delivery_type: 'digital', order_num: 9 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Eğitim belgesi ve Credentials Evaluation Raporu (ABD denkliği)', delivery_type: 'digital', order_num: 10 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Diploma / transkript (Apostilli, İngilizce tercümeli)', delivery_type: 'digital', order_num: 11 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Geçmiş iş deneyimi belgeleri ve referans mektupları', delivery_type: 'digital', order_num: 12 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Çalışma/İş Vizesi', doc_name: 'CV / Özgeçmiş (İngilizce)', delivery_type: 'digital', order_num: 13 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Adli sicil kaydı (Apostilli, İngilizce tercümeli)', delivery_type: 'digital', order_num: 14 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Nüfus kayıt örneği (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 15 },
  { country: 'Amerika Birleşik Devletleri', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Son 3 aylık banka hesap dökümü (banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 16 },
  // AVUSTURYA - Aile/Arkadaş Ziyareti
  { country: 'Avusturya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Pasaportun orijinali', delivery_type: 'physical', order_num: 1 },
  { country: 'Avusturya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Pasaport fotokopisi', delivery_type: 'digital', order_num: 2 },
  { country: 'Avusturya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Kimlik fotokopisi', delivery_type: 'digital', order_num: 3 },
  { country: 'Avusturya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: '1 adet biyometrik fotoğraf (35x45mm)', delivery_type: 'physical', order_num: 4 },
  { country: 'Avusturya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Vize başvuru formu (imzalı)', delivery_type: 'company', order_num: 5 },
  { country: 'Avusturya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 6 },
  { country: 'Avusturya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Gidiş-dönüş uçak bileti rezervasyonu', delivery_type: 'digital', order_num: 7 },
  { country: 'Avusturya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Seyahat sağlık sigortası (min. 30.000 €)', delivery_type: 'digital', order_num: 8 },
  { country: 'Avusturya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Son 3 aylık banka hesap dökümü (banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 9 },
  { country: 'Avusturya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Ev sahibinden davet mektubu', delivery_type: 'digital', order_num: 10 },
  { country: 'Avusturya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Ev sahibinin pasaport / oturma izni fotokopisi', delivery_type: 'digital', order_num: 11 },
  { country: 'Avusturya', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Akrabalık belgesi (tercümeli, Apostilli)', delivery_type: 'digital', order_num: 12 },
  // AVUSTURYA - Eğitim/Öğrenci
  { country: 'Avusturya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Pasaportun orijinali', delivery_type: 'physical', order_num: 1 },
  { country: 'Avusturya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Pasaport fotokopisi', delivery_type: 'digital', order_num: 2 },
  { country: 'Avusturya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Kimlik fotokopisi', delivery_type: 'digital', order_num: 3 },
  { country: 'Avusturya', visa_type: 'Eğitim/Öğrenci', doc_name: '1 adet biyometrik fotoğraf', delivery_type: 'physical', order_num: 4 },
  { country: 'Avusturya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Vize başvuru formu (imzalı)', delivery_type: 'company', order_num: 5 },
  { country: 'Avusturya', visa_type: 'Eğitim/Öğrenci', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 6 },
  { country: 'Avusturya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Nüfus kayıt örneği (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 7 },
  { country: 'Avusturya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Gidiş-dönüş uçak bileti rezervasyonu', delivery_type: 'digital', order_num: 8 },
  { country: 'Avusturya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Seyahat sağlık sigortası (min. 30.000 €)', delivery_type: 'digital', order_num: 9 },
  { country: 'Avusturya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Avusturya okul/üniversite kabul belgesi', delivery_type: 'digital', order_num: 10 },
  { country: 'Avusturya', visa_type: 'Eğitim/Öğrenci', doc_name: "Öğrenci belgesi (Türkiye'deki okul)", delivery_type: 'digital', order_num: 11 },
  { country: 'Avusturya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Burs belgesi (varsa)', delivery_type: 'digital', order_num: 12 },
  { country: 'Avusturya', visa_type: 'Eğitim/Öğrenci', doc_name: 'Veli/sponsor banka hesap dökümü (son 3 ay, banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 13 },
  // AVUSTURYA - Ticari/İş
  { country: 'Avusturya', visa_type: 'Ticari/İş', doc_name: 'Pasaportun orijinali', delivery_type: 'physical', order_num: 1 },
  { country: 'Avusturya', visa_type: 'Ticari/İş', doc_name: 'Pasaport fotokopisi', delivery_type: 'digital', order_num: 2 },
  { country: 'Avusturya', visa_type: 'Ticari/İş', doc_name: 'Kimlik fotokopisi', delivery_type: 'digital', order_num: 3 },
  { country: 'Avusturya', visa_type: 'Ticari/İş', doc_name: '1 adet biyometrik fotoğraf', delivery_type: 'physical', order_num: 4 },
  { country: 'Avusturya', visa_type: 'Ticari/İş', doc_name: 'Vize başvuru formu (imzalı)', delivery_type: 'company', order_num: 5 },
  { country: 'Avusturya', visa_type: 'Ticari/İş', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 6 },
  { country: 'Avusturya', visa_type: 'Ticari/İş', doc_name: 'Gidiş-dönüş uçak bileti rezervasyonu', delivery_type: 'digital', order_num: 7 },
  { country: 'Avusturya', visa_type: 'Ticari/İş', doc_name: 'Seyahat sağlık sigortası (min. 30.000 €)', delivery_type: 'digital', order_num: 8 },
  { country: 'Avusturya', visa_type: 'Ticari/İş', doc_name: "Avusturya'daki iş ortağından davet mektubu", delivery_type: 'digital', order_num: 9 },
  { country: 'Avusturya', visa_type: 'Ticari/İş', doc_name: 'İşveren görev yazısı', delivery_type: 'digital', order_num: 10 },
  { country: 'Avusturya', visa_type: 'Ticari/İş', doc_name: 'Şirket faaliyet belgesi (son 3 ay içinde alınmış, e-imzalı/orijinal)', delivery_type: 'digital', order_num: 11 },
  { country: 'Avusturya', visa_type: 'Ticari/İş', doc_name: 'Vergi levhası', delivery_type: 'digital', order_num: 12 },
  { country: 'Avusturya', visa_type: 'Ticari/İş', doc_name: 'Ticaret sicil gazetesi (son 6 ay içinde alınmış, tercümeli)', delivery_type: 'digital', order_num: 13 },
  { country: 'Avusturya', visa_type: 'Ticari/İş', doc_name: 'Son 3 aylık banka hesap dökümü (banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 14 },
  // AVUSTURYA - Turistik
  { country: 'Avusturya', visa_type: 'Turistik', doc_name: 'Pasaportun orijinali', delivery_type: 'physical', order_num: 1 },
  { country: 'Avusturya', visa_type: 'Turistik', doc_name: 'Pasaport fotokopisi', delivery_type: 'digital', order_num: 2 },
  { country: 'Avusturya', visa_type: 'Turistik', doc_name: 'Kimlik fotokopisi', delivery_type: 'digital', order_num: 3 },
  { country: 'Avusturya', visa_type: 'Turistik', doc_name: '1 adet biyometrik fotoğraf', delivery_type: 'physical', order_num: 4 },
  { country: 'Avusturya', visa_type: 'Turistik', doc_name: 'Vize başvuru formu (imzalı)', delivery_type: 'company', order_num: 5 },
  { country: 'Avusturya', visa_type: 'Turistik', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 6 },
  { country: 'Avusturya', visa_type: 'Turistik', doc_name: 'Nüfus kayıt örneği (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 7 },
  { country: 'Avusturya', visa_type: 'Turistik', doc_name: 'Gidiş-dönüş uçak bileti rezervasyonu', delivery_type: 'digital', order_num: 8 },
  { country: 'Avusturya', visa_type: 'Turistik', doc_name: 'Otel / konaklama rezervasyonu', delivery_type: 'digital', order_num: 9 },
  { country: 'Avusturya', visa_type: 'Turistik', doc_name: 'Seyahat sağlık sigortası (min. 30.000 €)', delivery_type: 'digital', order_num: 10 },
  { country: 'Avusturya', visa_type: 'Turistik', doc_name: 'İşveren İzin/Görev Yazısı — ZORUNLU (ıslak imzalı ve kaşeli; işe başlangıç tarihi, maaş, görev ve izin tarihleri belirtilmeli)', delivery_type: 'digital', order_num: 11 },
  { country: 'Avusturya', visa_type: 'Turistik', doc_name: 'SGK İşe Giriş Bildirgesi — ZORUNLU (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 12 },
  { country: 'Avusturya', visa_type: 'Turistik', doc_name: 'SGK Hizmet Dökümü (e-devlet, barkodlu; tüm sigorta geçmişini kapsar)', delivery_type: 'digital', order_num: 13 },
  { country: 'Avusturya', visa_type: 'Turistik', doc_name: 'Maaş bordrosu veya gelir belgesi', delivery_type: 'digital', order_num: 14 },
  { country: 'Avusturya', visa_type: 'Turistik', doc_name: 'Son 3 aylık banka hesap dökümü (banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 15 },
  // AVUSTURYA - Çalışma/İş Vizesi
  { country: 'Avusturya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Pasaportun orijinali (+ önceki pasaportlar)', delivery_type: 'physical', order_num: 1 },
  { country: 'Avusturya', visa_type: 'Çalışma/İş Vizesi', doc_name: '1 adet biyometrik fotoğraf (35x45mm, ICAO)', delivery_type: 'physical', order_num: 2 },
  { country: 'Avusturya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'D Tipi Vize / İkamet İzni Başvuru Formu', delivery_type: 'company', order_num: 3 },
  { country: 'Avusturya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 4 },
  { country: 'Avusturya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Tam vukuatlı nüfus kayıt örneği (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 5 },
  { country: 'Avusturya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Adli sicil kaydı (Apostilli, Almanca/İngilizce tercümeli)', delivery_type: 'digital', order_num: 6 },
  { country: 'Avusturya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'İşveren Beyanı — Arbeitgebererklärung (Avusturya işvereninin doldurduğu yasal istihdam formu)', delivery_type: 'digital', order_num: 7 },
  { country: 'Avusturya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'İş sözleşmesi (aylık brüt min. 3.465 € — 2026 Diğer Kilit İşçi eşiği)', delivery_type: 'digital', order_num: 8 },
  { country: 'Avusturya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Diploma ve mesleki sertifikalar (puan hesaplaması için, tercümeli)', delivery_type: 'digital', order_num: 9 },
  { country: 'Avusturya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Transkriptler / akademik belgeler', delivery_type: 'digital', order_num: 10 },
  { country: 'Avusturya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Dil sertifikası: Almanca (ÖSD/Goethe) veya İngilizce (IELTS/TOEFL)', delivery_type: 'digital', order_num: 11 },
  { country: 'Avusturya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Konaklama belgesi: kira sözleşmesi (Mietvertrag) veya konaklama taahhütnamesi', delivery_type: 'digital', order_num: 12 },
  { country: 'Avusturya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Geçim sağlama kanıtı (2026: tek kişi net min. 1.273,99 €/ay)', delivery_type: 'digital', order_num: 13 },
  { country: 'Avusturya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Doğum belgesi (Apostilli, tercümeli)', delivery_type: 'digital', order_num: 14 },
  { country: 'Avusturya', visa_type: 'Çalışma/İş Vizesi', doc_name: "Seyahat sağlık sigortası (Avusturya'da kapsamlı, min. 30.000 €)", delivery_type: 'digital', order_num: 15 },
  { country: 'Avusturya', visa_type: 'Çalışma/İş Vizesi', doc_name: 'CV / Özgeçmiş (Europass formatı)', delivery_type: 'digital', order_num: 16 },
  // BELÇİKA - Aile/Arkadaş Ziyareti
  { country: 'Belçika', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Pasaportun orijinali', delivery_type: 'physical', order_num: 1 },
  { country: 'Belçika', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Pasaport fotokopisi', delivery_type: 'digital', order_num: 2 },
  { country: 'Belçika', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Kimlik fotokopisi', delivery_type: 'digital', order_num: 3 },
  { country: 'Belçika', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: '2 adet biyometrik fotoğraf', delivery_type: 'physical', order_num: 4 },
  { country: 'Belçika', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Vize başvuru formu (imzalı)', delivery_type: 'company', order_num: 5 },
  { country: 'Belçika', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 6 },
  { country: 'Belçika', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Gidiş-dönüş uçak bileti rezervasyonu', delivery_type: 'digital', order_num: 7 },
  { country: 'Belçika', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Seyahat sağlık sigortası (min. 30.000 €)', delivery_type: 'digital', order_num: 8 },
  { country: 'Belçika', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Son 3 aylık banka hesap dökümü (banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 9 },
  { country: 'Belçika', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Ev sahibinden davet mektubu', delivery_type: 'digital', order_num: 10 },
  { country: 'Belçika', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Ev sahibinin pasaport / oturma izni fotokopisi', delivery_type: 'digital', order_num: 11 },
  { country: 'Belçika', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Akrabalık belgesi (tercümeli)', delivery_type: 'digital', order_num: 12 },
  // BELÇİKA - Eğitim/Öğrenci
  { country: 'Belçika', visa_type: 'Eğitim/Öğrenci', doc_name: 'Pasaportun orijinali', delivery_type: 'physical', order_num: 1 },
  { country: 'Belçika', visa_type: 'Eğitim/Öğrenci', doc_name: 'Pasaport fotokopisi', delivery_type: 'digital', order_num: 2 },
  { country: 'Belçika', visa_type: 'Eğitim/Öğrenci', doc_name: 'Kimlik fotokopisi', delivery_type: 'digital', order_num: 3 },
  { country: 'Belçika', visa_type: 'Eğitim/Öğrenci', doc_name: '2 adet biyometrik fotoğraf', delivery_type: 'physical', order_num: 4 },
  { country: 'Belçika', visa_type: 'Eğitim/Öğrenci', doc_name: 'Vize başvuru formu (imzalı)', delivery_type: 'company', order_num: 5 },
  { country: 'Belçika', visa_type: 'Eğitim/Öğrenci', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 6 },
  { country: 'Belçika', visa_type: 'Eğitim/Öğrenci', doc_name: 'Nüfus kayıt örneği (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 7 },
  { country: 'Belçika', visa_type: 'Eğitim/Öğrenci', doc_name: 'Seyahat sağlık sigortası (min. 30.000 €)', delivery_type: 'digital', order_num: 8 },
  { country: 'Belçika', visa_type: 'Eğitim/Öğrenci', doc_name: 'Belçika okul/üniversite kabul belgesi', delivery_type: 'digital', order_num: 9 },
  { country: 'Belçika', visa_type: 'Eğitim/Öğrenci', doc_name: 'Öğrenci belgesi', delivery_type: 'digital', order_num: 10 },
  { country: 'Belçika', visa_type: 'Eğitim/Öğrenci', doc_name: 'Burs belgesi (varsa)', delivery_type: 'digital', order_num: 11 },
  { country: 'Belçika', visa_type: 'Eğitim/Öğrenci', doc_name: 'Veli/sponsor banka hesap dökümü (son 3 ay, banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 12 },
  // BELÇİKA - Ticari/İş
  { country: 'Belçika', visa_type: 'Ticari/İş', doc_name: 'Pasaportun orijinali', delivery_type: 'physical', order_num: 1 },
  { country: 'Belçika', visa_type: 'Ticari/İş', doc_name: 'Pasaport fotokopisi', delivery_type: 'digital', order_num: 2 },
  { country: 'Belçika', visa_type: 'Ticari/İş', doc_name: 'Kimlik fotokopisi', delivery_type: 'digital', order_num: 3 },
  { country: 'Belçika', visa_type: 'Ticari/İş', doc_name: '2 adet biyometrik fotoğraf', delivery_type: 'physical', order_num: 4 },
  { country: 'Belçika', visa_type: 'Ticari/İş', doc_name: 'Vize başvuru formu (imzalı)', delivery_type: 'company', order_num: 5 },
  { country: 'Belçika', visa_type: 'Ticari/İş', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 6 },
  { country: 'Belçika', visa_type: 'Ticari/İş', doc_name: 'Gidiş-dönüş uçak bileti rezervasyonu', delivery_type: 'digital', order_num: 7 },
  { country: 'Belçika', visa_type: 'Ticari/İş', doc_name: 'Seyahat sağlık sigortası (min. 30.000 €)', delivery_type: 'digital', order_num: 8 },
  { country: 'Belçika', visa_type: 'Ticari/İş', doc_name: "Belçika'daki iş ortağından davet mektubu", delivery_type: 'digital', order_num: 9 },
  { country: 'Belçika', visa_type: 'Ticari/İş', doc_name: 'İşveren görev yazısı', delivery_type: 'digital', order_num: 10 },
  { country: 'Belçika', visa_type: 'Ticari/İş', doc_name: 'Şirket faaliyet belgesi (son 3 ay içinde alınmış, e-imzalı/orijinal)', delivery_type: 'digital', order_num: 11 },
  { country: 'Belçika', visa_type: 'Ticari/İş', doc_name: 'Vergi levhası', delivery_type: 'digital', order_num: 12 },
  { country: 'Belçika', visa_type: 'Ticari/İş', doc_name: 'Ticaret sicil gazetesi (son 6 ay içinde alınmış, tercümeli)', delivery_type: 'digital', order_num: 13 },
  { country: 'Belçika', visa_type: 'Ticari/İş', doc_name: 'Son 3 aylık banka hesap dökümü (banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 14 },
  // BELÇİKA - Turistik
  { country: 'Belçika', visa_type: 'Turistik', doc_name: 'Pasaportun orijinali', delivery_type: 'physical', order_num: 1 },
  { country: 'Belçika', visa_type: 'Turistik', doc_name: 'Pasaport fotokopisi', delivery_type: 'digital', order_num: 2 },
  { country: 'Belçika', visa_type: 'Turistik', doc_name: 'Kimlik fotokopisi', delivery_type: 'digital', order_num: 3 },
  { country: 'Belçika', visa_type: 'Turistik', doc_name: '2 adet biyometrik fotoğraf', delivery_type: 'physical', order_num: 4 },
  { country: 'Belçika', visa_type: 'Turistik', doc_name: 'Vize başvuru formu (çevrimiçi doldurulmuş, imzalı)', delivery_type: 'company', order_num: 5 },
  { country: 'Belçika', visa_type: 'Turistik', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 6 },
  { country: 'Belçika', visa_type: 'Turistik', doc_name: 'Nüfus kayıt örneği (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 7 },
  { country: 'Belçika', visa_type: 'Turistik', doc_name: 'Gidiş-dönüş uçak bileti rezervasyonu', delivery_type: 'digital', order_num: 8 },
  { country: 'Belçika', visa_type: 'Turistik', doc_name: 'Otel / konaklama rezervasyonu', delivery_type: 'digital', order_num: 9 },
  { country: 'Belçika', visa_type: 'Turistik', doc_name: 'Seyahat sağlık sigortası (min. 30.000 €)', delivery_type: 'digital', order_num: 10 },
  { country: 'Belçika', visa_type: 'Turistik', doc_name: 'İşveren İzin/Görev Yazısı — ZORUNLU (ıslak imzalı ve kaşeli; işe başlangıç tarihi, maaş, görev ve izin tarihleri belirtilmeli)', delivery_type: 'digital', order_num: 11 },
  { country: 'Belçika', visa_type: 'Turistik', doc_name: 'SGK İşe Giriş Bildirgesi — ZORUNLU (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 12 },
  { country: 'Belçika', visa_type: 'Turistik', doc_name: 'SGK Hizmet Dökümü (e-devlet, barkodlu; tüm sigorta geçmişini kapsar)', delivery_type: 'digital', order_num: 13 },
  { country: 'Belçika', visa_type: 'Turistik', doc_name: 'Maaş bordrosu veya gelir belgesi', delivery_type: 'digital', order_num: 14 },
  { country: 'Belçika', visa_type: 'Turistik', doc_name: 'Son 3 aylık banka hesap dökümü (banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 15 },
  // BELÇİKA - Çalışma/İş Vizesi
  { country: 'Belçika', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Pasaportun orijinali (min. 12 ay geçerli, 2 boş sayfa)', delivery_type: 'physical', order_num: 1 },
  { country: 'Belçika', visa_type: 'Çalışma/İş Vizesi', doc_name: '2 adet biyometrik fotoğraf (35x45mm, beyaz/açık fon)', delivery_type: 'physical', order_num: 2 },
  { country: 'Belçika', visa_type: 'Çalışma/İş Vizesi', doc_name: 'D Tipi Vize Başvuru Formu — VisaOnWeb üzerinden (imzalı)', delivery_type: 'company', order_num: 3 },
  { country: 'Belçika', visa_type: 'Çalışma/İş Vizesi', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 4 },
  { country: 'Belçika', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Tam vukuatlı nüfus kayıt örneği (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 5 },
  { country: 'Belçika', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Adli sicil kaydı (Apostilli, Fransızca/Flemenkçe/İngilizce tercümeli)', delivery_type: 'digital', order_num: 6 },
  { country: 'Belçika', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Single Permit / Annexe 46 Karar Belgesi (işverenin VDAB/FOREM/Actiris\'ten aldığı onay)', delivery_type: 'digital', order_num: 7 },
  { country: 'Belçika', visa_type: 'Çalışma/İş Vizesi', doc_name: 'İş sözleşmesi (Belçika iş hukukuna uygun, tercümeli)', delivery_type: 'digital', order_num: 8 },
  { country: 'Belçika', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Diploma denkliği belgesi (Flaman veya Valon topluluğu onaylı)', delivery_type: 'digital', order_num: 9 },
  { country: 'Belçika', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Sağlık raporu — Medical Certificate (konsolosluğun anlaşmalı hastanelerinden)', delivery_type: 'digital', order_num: 10 },
  { country: 'Belçika', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Doğum belgesi (Apostilli, tercümeli)', delivery_type: 'digital', order_num: 11 },
  { country: 'Belçika', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Konaklama belgesi (kira sözleşmesi veya taahhütname)', delivery_type: 'digital', order_num: 12 },
  { country: 'Belçika', visa_type: 'Çalışma/İş Vizesi', doc_name: 'CV / Özgeçmiş (Fransızca veya Flemenkçe)', delivery_type: 'digital', order_num: 13 },
  // BULGARİSTAN - Aile/Arkadaş Ziyareti
  { country: 'Bulgaristan', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Pasaportun orijinali', delivery_type: 'physical', order_num: 1 },
  { country: 'Bulgaristan', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Pasaport fotokopisi', delivery_type: 'digital', order_num: 2 },
  { country: 'Bulgaristan', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Kimlik fotokopisi', delivery_type: 'digital', order_num: 3 },
  { country: 'Bulgaristan', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: '2 adet biyometrik fotoğraf', delivery_type: 'physical', order_num: 4 },
  { country: 'Bulgaristan', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Vize başvuru formu (imzalı)', delivery_type: 'company', order_num: 5 },
  { country: 'Bulgaristan', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 6 },
  { country: 'Bulgaristan', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Gidiş-dönüş uçak bileti rezervasyonu', delivery_type: 'digital', order_num: 7 },
  { country: 'Bulgaristan', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Seyahat sağlık sigortası (min. 30.000 €)', delivery_type: 'digital', order_num: 8 },
  { country: 'Bulgaristan', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Son 3 aylık banka hesap dökümü (banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 9 },
  { country: 'Bulgaristan', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Ev sahibinden davet mektubu', delivery_type: 'digital', order_num: 10 },
  { country: 'Bulgaristan', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Ev sahibinin pasaport / oturma izni fotokopisi', delivery_type: 'digital', order_num: 11 },
  { country: 'Bulgaristan', visa_type: 'Aile/Arkadaş Ziyareti', doc_name: 'Akrabalık belgesi (tercümeli)', delivery_type: 'digital', order_num: 12 },
  // BULGARİSTAN - Eğitim/Öğrenci
  { country: 'Bulgaristan', visa_type: 'Eğitim/Öğrenci', doc_name: 'Pasaportun orijinali', delivery_type: 'physical', order_num: 1 },
  { country: 'Bulgaristan', visa_type: 'Eğitim/Öğrenci', doc_name: 'Pasaport fotokopisi', delivery_type: 'digital', order_num: 2 },
  { country: 'Bulgaristan', visa_type: 'Eğitim/Öğrenci', doc_name: 'Kimlik fotokopisi', delivery_type: 'digital', order_num: 3 },
  { country: 'Bulgaristan', visa_type: 'Eğitim/Öğrenci', doc_name: '2 adet biyometrik fotoğraf', delivery_type: 'physical', order_num: 4 },
  { country: 'Bulgaristan', visa_type: 'Eğitim/Öğrenci', doc_name: 'Vize başvuru formu (imzalı)', delivery_type: 'company', order_num: 5 },
  { country: 'Bulgaristan', visa_type: 'Eğitim/Öğrenci', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 6 },
  { country: 'Bulgaristan', visa_type: 'Eğitim/Öğrenci', doc_name: 'Nüfus kayıt örneği (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 7 },
  { country: 'Bulgaristan', visa_type: 'Eğitim/Öğrenci', doc_name: 'Seyahat sağlık sigortası (min. 30.000 €)', delivery_type: 'digital', order_num: 8 },
  { country: 'Bulgaristan', visa_type: 'Eğitim/Öğrenci', doc_name: 'Bulgaristan okul/üniversite kabul belgesi', delivery_type: 'digital', order_num: 9 },
  { country: 'Bulgaristan', visa_type: 'Eğitim/Öğrenci', doc_name: 'Öğrenci belgesi', delivery_type: 'digital', order_num: 10 },
  { country: 'Bulgaristan', visa_type: 'Eğitim/Öğrenci', doc_name: 'Burs belgesi (varsa)', delivery_type: 'digital', order_num: 11 },
  { country: 'Bulgaristan', visa_type: 'Eğitim/Öğrenci', doc_name: 'Veli/sponsor banka hesap dökümü (son 3 ay, banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 12 },
  // BULGARİSTAN - Ticari/İş
  { country: 'Bulgaristan', visa_type: 'Ticari/İş', doc_name: 'Pasaportun orijinali', delivery_type: 'physical', order_num: 1 },
  { country: 'Bulgaristan', visa_type: 'Ticari/İş', doc_name: 'Pasaport fotokopisi', delivery_type: 'digital', order_num: 2 },
  { country: 'Bulgaristan', visa_type: 'Ticari/İş', doc_name: 'Kimlik fotokopisi', delivery_type: 'digital', order_num: 3 },
  { country: 'Bulgaristan', visa_type: 'Ticari/İş', doc_name: '2 adet biyometrik fotoğraf', delivery_type: 'physical', order_num: 4 },
  { country: 'Bulgaristan', visa_type: 'Ticari/İş', doc_name: 'Vize başvuru formu (imzalı)', delivery_type: 'company', order_num: 5 },
  { country: 'Bulgaristan', visa_type: 'Ticari/İş', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 6 },
  { country: 'Bulgaristan', visa_type: 'Ticari/İş', doc_name: 'Gidiş-dönüş uçak bileti rezervasyonu', delivery_type: 'digital', order_num: 7 },
  { country: 'Bulgaristan', visa_type: 'Ticari/İş', doc_name: 'Seyahat sağlık sigortası (min. 30.000 €)', delivery_type: 'digital', order_num: 8 },
  { country: 'Bulgaristan', visa_type: 'Ticari/İş', doc_name: "Bulgaristan'daki iş ortağından davet mektubu", delivery_type: 'digital', order_num: 9 },
  { country: 'Bulgaristan', visa_type: 'Ticari/İş', doc_name: 'İşveren görev yazısı', delivery_type: 'digital', order_num: 10 },
  { country: 'Bulgaristan', visa_type: 'Ticari/İş', doc_name: 'Şirket faaliyet belgesi (son 3 ay içinde alınmış, e-imzalı/orijinal)', delivery_type: 'digital', order_num: 11 },
  { country: 'Bulgaristan', visa_type: 'Ticari/İş', doc_name: 'Vergi levhası', delivery_type: 'digital', order_num: 12 },
  { country: 'Bulgaristan', visa_type: 'Ticari/İş', doc_name: 'Ticaret sicil gazetesi (son 6 ay içinde alınmış, tercümeli)', delivery_type: 'digital', order_num: 13 },
  { country: 'Bulgaristan', visa_type: 'Ticari/İş', doc_name: 'Son 3 aylık banka hesap dökümü (banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 14 },
  // BULGARİSTAN - Turistik
  { country: 'Bulgaristan', visa_type: 'Turistik', doc_name: 'Pasaportun orijinali', delivery_type: 'physical', order_num: 1 },
  { country: 'Bulgaristan', visa_type: 'Turistik', doc_name: 'Pasaport fotokopisi', delivery_type: 'digital', order_num: 2 },
  { country: 'Bulgaristan', visa_type: 'Turistik', doc_name: 'Kimlik fotokopisi', delivery_type: 'digital', order_num: 3 },
  { country: 'Bulgaristan', visa_type: 'Turistik', doc_name: '2 adet biyometrik fotoğraf', delivery_type: 'physical', order_num: 4 },
  { country: 'Bulgaristan', visa_type: 'Turistik', doc_name: 'Vize başvuru formu (imzalı)', delivery_type: 'company', order_num: 5 },
  { country: 'Bulgaristan', visa_type: 'Turistik', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 6 },
  { country: 'Bulgaristan', visa_type: 'Turistik', doc_name: 'Nüfus kayıt örneği (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 7 },
  { country: 'Bulgaristan', visa_type: 'Turistik', doc_name: 'Gidiş-dönüş uçak bileti rezervasyonu', delivery_type: 'digital', order_num: 8 },
  { country: 'Bulgaristan', visa_type: 'Turistik', doc_name: 'Otel / konaklama rezervasyonu', delivery_type: 'digital', order_num: 9 },
  { country: 'Bulgaristan', visa_type: 'Turistik', doc_name: 'Seyahat sağlık sigortası (min. 30.000 €)', delivery_type: 'digital', order_num: 10 },
  { country: 'Bulgaristan', visa_type: 'Turistik', doc_name: 'İşveren İzin/Görev Yazısı — ZORUNLU (ıslak imzalı ve kaşeli; işe başlangıç tarihi, maaş, görev ve izin tarihleri belirtilmeli)', delivery_type: 'digital', order_num: 11 },
  { country: 'Bulgaristan', visa_type: 'Turistik', doc_name: 'SGK İşe Giriş Bildirgesi — ZORUNLU (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 12 },
  { country: 'Bulgaristan', visa_type: 'Turistik', doc_name: 'SGK Hizmet Dökümü (e-devlet, barkodlu; tüm sigorta geçmişini kapsar)', delivery_type: 'digital', order_num: 13 },
  { country: 'Bulgaristan', visa_type: 'Turistik', doc_name: 'Maaş bordrosu veya gelir belgesi', delivery_type: 'digital', order_num: 14 },
  { country: 'Bulgaristan', visa_type: 'Turistik', doc_name: 'Son 3 aylık banka hesap dökümü (banka kaşeli/imzalı; yanına Banka İmza Sirküleri / Banka Yetki Belgesi eklenmeli)', delivery_type: 'digital', order_num: 15 },
  // BULGARİSTAN - Çalışma/İş Vizesi
  { country: 'Bulgaristan', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Pasaportun orijinali (min. 18 ay geçerli, 2 boş sayfa)', delivery_type: 'physical', order_num: 1 },
  { country: 'Bulgaristan', visa_type: 'Çalışma/İş Vizesi', doc_name: '2 adet biyometrik fotoğraf', delivery_type: 'physical', order_num: 2 },
  { country: 'Bulgaristan', visa_type: 'Çalışma/İş Vizesi', doc_name: 'D Tipi Ulusal Vize Başvuru Formu', delivery_type: 'company', order_num: 3 },
  { country: 'Bulgaristan', visa_type: 'Çalışma/İş Vizesi', doc_name: 'İkametgah belgesi (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 4 },
  { country: 'Bulgaristan', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Tam vukuatlı nüfus kayıt örneği (e-devlet, barkodlu)', delivery_type: 'digital', order_num: 5 },
  { country: 'Bulgaristan', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Adli sicil kaydı (Apostilli, Bulgarca/İngilizce tercümeli)', delivery_type: 'digital', order_num: 6 },
  { country: 'Bulgaristan', visa_type: 'Çalışma/İş Vizesi', doc_name: "Bulgaristan İstihdam Ajansı Onay Belgesi (işverenin Çalışma Bakanlığı'ndan aldığı çalışma izni)", delivery_type: 'digital', order_num: 7 },
  { country: 'Bulgaristan', visa_type: 'Çalışma/İş Vizesi', doc_name: 'İş sözleşmesi (Bulgar mevzuatına uygun, tercümeli)', delivery_type: 'digital', order_num: 8 },
  { country: 'Bulgaristan', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Şirket faaliyet belgesi (Bulgar işverenin güncel vergi levhası ve Ticaret Odası kaydı)', delivery_type: 'digital', order_num: 9 },
  { country: 'Bulgaristan', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Diploma ve mesleki yeterlilik belgeleri (tercümeli, Apostilli)', delivery_type: 'digital', order_num: 10 },
  { country: 'Bulgaristan', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Konaklama sözleşmesi (noter onaylı kira sözleşmesi veya taahhütname)', delivery_type: 'digital', order_num: 11 },
  { country: 'Bulgaristan', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Banka hesap dökümü (geçimi karşılayacak düzeyde; min. 1.077 BGN/ay — 2026 asgari ücret)', delivery_type: 'digital', order_num: 12 },
  { country: 'Bulgaristan', visa_type: 'Çalışma/İş Vizesi', doc_name: "Sağlık sigortası (Bulgaristan'da geçerli poliçe)", delivery_type: 'digital', order_num: 13 },
  { country: 'Bulgaristan', visa_type: 'Çalışma/İş Vizesi', doc_name: 'Doğum belgesi (Apostilli, tercümeli)', delivery_type: 'digital', order_num: 14 },
  { country: 'Bulgaristan', visa_type: 'Çalışma/İş Vizesi', doc_name: 'CV / Özgeçmiş (Bulgarca veya İngilizce)', delivery_type: 'digital', order_num: 15 },
];

async function run() {
  console.log('Tüm visa_documents siliniyor...');
  const { error: deleteError } = await supabase
    .from('visa_documents')
    .delete()
    .gte('order_num', 0);

  if (deleteError) {
    console.error('Silme hatası:', deleteError);
    process.exit(1);
  }
  console.log('Silme tamamlandı.');

  const BATCH_SIZE = 50;
  let inserted = 0;
  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE);
    const { error: insertError } = await supabase
      .from('visa_documents')
      .insert(batch);
    if (insertError) {
      console.error(`Batch ${i}-${i + BATCH_SIZE} insert hatası:`, insertError);
      process.exit(1);
    }
    inserted += batch.length;
    console.log(`${inserted}/${rows.length} satır eklendi...`);
  }

  console.log(`\nTamamlandı! Toplam ${rows.length} satır eklendi.`);

  const { count } = await supabase
    .from('visa_documents')
    .select('*', { count: 'exact', head: true });
  console.log(`Tablodaki toplam satır: ${count}`);
}

run().catch(console.error);
